apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  selector:
    matchLabels:
      app: zomato
  replicas: 2 
  template: 
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: sandeeepdocker7/zomato:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zomato
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
